### PR TITLE
Add AppIcon to ResetTransmitter

### PR DESCRIPTION
**Pull request by achkars**
Following up on PR #142

### CODE REVIEW

**Comment by achkars** [comment]
I'm opened to discussing modifications to the design if required.

**Comment by ps2** [comment]
How about a simple white background, with the Loop bg blue color as the foreground.

**Comment by achkars** [comment]
DexcomReset-LoopBlue

**Comment by achkars** [comment]
Looks decent
DexcomReset-LoopBlue128

**Comment by ps2** [comment]
Yeah, I like that.

**Comment by achkars** [comment]
It's been updated

**Pull request merged**
