### PR TITLE
Writes last read glucose to icon badge

### PR DESCRIPTION
**Pull request by dennisgove**
If able to read a glucose value then will write it to the app badge. If error in reading then clears badge.

Nothing fancy here but thought I'd share with you what I added today.

### CODE REVIEW

**Comment by dennisgove** [comment]
Actually, I don't think this will work while the app is closed.

**Comment by dennisgove** [comment]
Nevermind. Confirmed that it properly updates the badge value when the app is running, closed and phone unlocked, closed and phone locked, closed and another app open. My previous comment was related to an error I saw related to setting the badge value when the app was closed.

**Comment by loudnate** [comment]
Thank you for adding this, Dennis. Please know that the example app is not intended to be use for therapy, but merely as an example and test harness for the xDripG5 framework. 

I'm out of the country this week but I intend to provide support for Carthage and CocoaPods so you can easily build your own apps on top of this data.

**Comment by loudnate** [comment]
I appreciate the PR, but I'm not going to merge it into the test app simply because I want to keep it as minimal as possible for others to understand the code in context, especially for those who have expressed interest in porting this to other platforms.

I would love to link to your app in the README as a great example of some use cases that freeing this data provides.

:beers:

**Comment by dennisgove** [comment]
Thanks very much. I've put my project at https://github.com/dennisgove/glucose-badge. I'm happy to credit you in anyway you'd like - currently in the README.

**Comment by loudnate** [comment]
That's great! I will open an issue now to write the README, and remind myself to link to your project.

Another simple single-use app would be one to put live data into HealthKit, and then optionally bulk-delete records (supported in iOS 9) older than 3 hours once the Dexcom app inserts them.

**Pull request closed without merging**
